version: "3.3"
services:
   nginx:
      depends_on:
         - pgsql
         - php
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./nginx
      environment:
         TZ: America/Argentina/Buenos_Aires
      ports:
         - '80:80'
      volumes:
         - ./yii-application:/var/www/html/
      container_name: yii2_ngnix
      networks:
         - yii-network

   pgsql:
      build:
         dockerfile: Dockerfile
         context: ./pgsql
      restart: always
      environment:
         POSTGRES_USER: "dev"
         POSTGRES_PASSWORD: "d3v"
         POSTGRES_DB: "unsplash"
      ports:
         - '5432:5432'
      volumes:
         - "./var/lib/pgdata:/var/lib/postgresql/data:rw"
         # - ./pgsql/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
      container_name: yii2_pgsql
      networks:
         - yii-network
   php:
      depends_on:
         - pgsql
         - redis
         - selenium-hub
         - mail
      restart: always
      build:
         dockerfile: Dockerfile
         context: ./php
         args:
            UID: 1000
            GID: 1000
      ports:
         - '9002:9000'      
      volumes:
         - "./yii-application:/var/www/html/"
      container_name: yii2_php
      networks:
         - yii-network

   redis:
      build:
         dockerfile: Dockerfile
         context: ./redis
      container_name: yii2_redis
      ports:
         - '6379:6379'
      networks:
         - yii-network

   mail:
      container_name: yii2_mail
      build:
         dockerfile: Dockerfile
         context: ./mailhog
      logging:
         driver: 'none'
      ports:
         - 1025:1025 # smtp server
         - 8025:8025 # web
      networks:
         - yii-network

   selenium-hub:
      image: selenium/hub:3.141
      container_name: selenium-hub
      ports:
         - "4444:4444"
      expose: 
         - 4444
      networks:
         - yii-network
      
networks:
   yii-network:
      driver: bridge