version: "3.3"
services:
   nginx:
      depends_on:
         - pgsql
         - php
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./nginx
      environment:
         TZ: America/Argentina/Buenos_Aires
      ports:
         - '8081:80'
      volumes:
         - ./files:/var/www/html/
      container_name: yii2_test_ngnix
   pgsql:
      build:
         dockerfile: Dockerfile
         context: ./pgsql
      restart: always
      environment:
         POSTGRES_USER: "root"
         POSTGRES_PASSWORD: "root"
         POSTGRES_DB: "test"
      ports:
         - '5432:5432'
      volumes:
         - "./var/lib/pgdata:/var/lib/postgresql/data"
      container_name: yii2_test_pgsql
   php:
      depends_on:
         - redis
         - mail
      restart: always
      build:
         dockerfile: Dockerfile
         context: ./php
         args:
            UID: 1000
            GID: 1000
      ports:
         - '9002:9000'      
      volumes:
         - "./files:/var/www/html/"
      container_name: yii2_test_php
   redis:
      build:
         dockerfile: Dockerfile
         context: ./redis
      container_name: yii2_test_redis
   mail:
      build:
         dockerfile: Dockerfile
         context: ./mailhog
      logging:
         driver: 'none'
      ports:
         - 1025:1025 # smtp server
         - 8025:8025 # web
      
